### PR TITLE
Python Development on M1 Macs

### PR DESCRIPTION
**Pull request by SaranjeetKaur**
To do:

- [x] update code blocks
- [x] update author
- [x] include hyperlinks
- [x] check if `mkdocs serve` works locally

### CODE REVIEW

**Review by AdrianDAlessandro — APPROVED** [review]
I've made changes and am happy with it. Note that I've added some MkDocs extensions that I think really add to the post and allow us to do some more fun things with the blog. Namely:
- [Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)
- [Code Blocks](https://squidfunk.github.io/mkdocs-material/reference/code-blocks)

**Review by alexdewar — APPROVED** [review]
LGTM! The formatting is much nicer than it was with Wordpress too.

**Review by dalonsoa — APPROVED** [review]
The extra extensions give this a very nice look will be very useful in the future, if we remember to use them. 

Maybe @SaranjeetKaur or @Sahil590 , mention in the guidelines about the extensions we are using, in particular the admonitions?

**Comment by SaranjeetKaur** [comment]
> The extra extensions give this a very nice look will be very useful in the future, if we remember to use them.
> 
> Maybe @SaranjeetKaur or @Sahil590 , mention in the guidelines about the extensions we are using, in particular the admonitions?

@dalonsoa yes, this was suggested by @AdrianDAlessandro yesterday and I am already capturing it on a pull request  https://github.com/ImperialCollegeLondon/RSEBlog/pull/41

**Pull request merged**
